# Generated by Django 3.0.5 on 2020-05-03 15:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('seller_name', models.CharField(blank=True, default='', max_length=128, null=True)),
                ('seller_code', models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=256, null=True)),
                ('client_id', models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True)),
                ('client_secret_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('access_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sellers',
            },
        ),
    ]
