version: '3'
services:
  web:
    build: .
    command: ["sh", "/code/start.sh"]
    volumes:
      - .:/code
      - /var/log/boloo:/var/log/boloo
      - /static/boloo:/static/boloo
      - /home/ubuntu/mapping:/mapping
    expose:
      - "26000"
    ports:
      - "26000:26000"
    restart: always
  
  celery:
    build: .
    command: celery -A boloo worker -l info
    #command: celery worker --app=boloo --queues=celery,sms,otp
    volumes:
      - .:/code
    restart: always
