# Generated by Django 3.0.5 on 2020-05-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipmentId', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('shipmentDate', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportId', models.IntegerField(blank=True, null=True)),
                ('transporterCode', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('trackAndTrace', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.Shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderItemId', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('orderId', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('orderDate', models.DateTimeField(auto_now=True)),
                ('latestDeliveryDate', models.DateTimeField(auto_now=True)),
                ('ean', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('offerPrice', models.FloatField(blank=True, null=True)),
                ('offerCondition', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fulfilmentMethod', models.CharField(blank=True, choices=[(None, 'Choose a preferred language.'), ('FBR', ' Fulfilled by the retailer'), ('FBB', 'Fulfilled by bol.com')], default=None, max_length=10, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.Shipment')),
            ],
        ),
    ]
